### PR TITLE
fix(http): add an http status code check for Warp queries

### LINKED ISSUE #3: Bad response status code on error
Current behaviour:

Make a TSL query a bad token, the response code will be 200 but the body says (in HTML): ...bad token..

Expected: TSL should return an errored status code (500 / 418 / ...)

https://github.com/ovh/tsl/blob/7ee52b5a3bbf9b3edd8c30091b311a4010c03ad1/tsl/controller.go#L251

### PR DESCRIPTION
**Pull request by aurrelhebert**
fixes #3 
Signed-off-by: Aurelien Hebert <aurelien.hebert@corp.ovh.com>

### CODE REVIEW

File: tsl/controller.go [hunk 1]
```diff
@@ -185,7 +185,7 @@ func promQuery(instructions []Instruction, prom string, ctx echo.Context, now ti
 		protoParser := ProtoParser{name: "prometheus", lineStart: lineStart}
 		promQl, err := protoParser.GeneratePromQl(instruction, now)
 		if err != nil {
-			log.Warn(err)
+			log.Debug(err)
```
Comment (FlorentinDUBOIS) [inline tsl/controller.go]: log.WithError(err).Error("Could not generate PromQL")

File: tsl/controller.go [hunk 2]
```diff
@@ -223,7 +223,7 @@ func warpQuery(instructions []Instruction, warp string, ctx echo.Context, lineSt
 	req.Body = warpscript
 	res, err := exec(req, warp, ctx)
 	if err != nil {
-		log.Warn(err)
+		log.Debug(err)
```
Comment (FlorentinDUBOIS) [inline tsl/controller.go]: log.WithError(err).Error("Could not execute WarpScript")

**Review by FlorentinDUBOIS — CHANGES_REQUESTED** [review]

**Review by PierreZ — APPROVED** [review]

**Review by StevenLeRoux — APPROVED** [review]

File: tsl/controller.go [hunk 3]
```diff
@@ -249,6 +249,10 @@ func exec(req *Request, warp string, ctx echo.Context) (string, error) {
 		return "", err
 	}
 
+	if http.StatusOK != res.StatusCode {
+		return "", errors.New(res.Header.Get("X-Warp10-Error-Message"))
```
Comment (miton18) [inline tsl/controller.go]: in case of Warp, you have an interesting `X-Warp10-Error-Message`

**Review by miton18 — APPROVED** [review]

**Review by FlorentinDUBOIS — APPROVED** [review]
